create table if not exists public.website_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  event_name text not null,
  path text not null default '/',
  section text,
  referrer_host text,
  device_type text not null default 'desktop',
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists website_events_created_at_idx on public.website_events (created_at desc);
create index if not exists website_events_session_idx on public.website_events (session_id, created_at);
alter table public.website_events enable row level security;

drop policy if exists "Owners can view website analytics" on public.website_events;
create policy "Owners can view website analytics"
on public.website_events for select to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = auth.uid() and sp.active = true and sp.role = 'owner'
));

revoke insert, update, delete on public.website_events from anon, authenticated;
grant select on public.website_events to authenticated;
